channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.4.1
  - ca-certificates=2021.10.8
  - click=8.0.3
  - django=3.2.9
  - django-cors-headers=3.9.0
  - djangorestframework=3.12.4
  - docutils=0.18
  - flake8=4.0.1
  - gunicorn=20.1.0
  - importlib-metadata=3.10.1
  - krb5=1.19.2
  - libcxx=12.0.1
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libpq=13.3
  - libzlib=1.2.11
  - mccabe=0.6.1
  - ncurses=6.2
  - openssl=1.1.1l
  - pip=21.3.1
  - psycopg2=2.9.1
  - pycodestyle=2.8.0
  - pyflakes=2.4.0
  - python=3.9.7
  - python-dotenv=0.19.1
  - python_abi=3.9
  - pytz=2021.3
  - readline=8.1
  - setuptools=58.5.3
  - sqlite=3.36.0
  - sqlparse=0.4.2
  - tk=8.6.11
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - yapf=0.31.0
  - zipp=3.6.0
  - zlib=1.2.11
